### ISSUE TITLE
Hardcoded Directory Path to pe_lib

### ISSUE THREAD

**Issue by ThomasThelen** [Kirbiflint50/KirbiDSM#1]
I noticed there's a hardcoded directory path for `Additional Include Directories`. This should be a relative path, and the path also currently reveals your name...

**Comment by Kirbiflint50** [comment]
Which part of the code? I'll fix it

**Comment by ThomasThelen** [comment]
It's not in the code, it's you visual studio targets. Check my pull request on 
https://github.com/Kirbiflint50/First-calculator-in-C--

**Comment by Kirbiflint50** [comment]
In the .sln file?

**Comment by ThomasThelen** [comment]
Look at the files that I changed, it's the `.vcxproj`

https://github.com/Kirbiflint50/First-calculator-in-C--/pull/2/files

**Comment by Kirbiflint50** [comment]
Ah ok, now I understood, thanks for help though :)
